<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="shushudelichendebijibendiannao.local" ignored="0" name="Store Circle Sync Tests" tests="3" failures="2" timestamp="2025-03-04T13:41:21 CST" time="15.342" errors="0">
  <testcase name="testCircleSync_InvalidField" time="5.097" classname="com.saas.qa.api.testcase.open.circle.StoreCircleSyncTest">
    <failure type="java.lang.AssertionError" message="结果不符合预期 expected [未找到该门店渠道表数据] but found [delFlg不为null,circleDTO={&amp;quot;channelId&amp;quot;:999,&amp;quot;circleId&amp;quot;:&amp;quot;test_circle_001&amp;quot;,&amp;quot;deliveryServiceType&amp;quot;:9,&amp;quot;enabled&amp;quot;:1,&amp;quot;fee&amp;quot;:5000,&amp;quot;feeType&amp;quot;:1,&amp;quot;name&amp;quot;:&amp;quot;测试服务圈&amp;quot;,&amp;quot;saasCircleId&amp;quot;:1001,&amp;quot;saasStoreId&amp;quot;:7315,&amp;quot;storeId&amp;quot;:&amp;quot;test57_hello&amp;quot;}]">
        <![CDATA[java.lang.AssertionError: 结果不符合预期 expected [未找到该门店渠道表数据] but found [delFlg不为null,circleDTO={"channelId":999,"circleId":"test_circle_001","deliveryServiceType":9,"enabled":1,"fee":5000,"feeType":1,"name":"测试服务圈","saasCircleId":1001,"saasStoreId":7315,"storeId":"test57_hello"}]
at com.saas.qa.api.testcase.open.circle.StoreCircleSyncTest.testCircleSync_InvalidField(StoreCircleSyncTest.java:90)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at com.saas.qa.api.utils.TestReportGenerator.runTests(TestReportGenerator.java:73)
at com.saas.qa.api.utils.TestReportGenerator.generateAndOpenReport(TestReportGenerator.java:53)
at com.saas.qa.api.utils.TestReportGenerator.main(TestReportGenerator.java:154)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testCircleSync_InvalidField -->
  <testcase name="testCircleSync_MissingRequired" time="5.091" classname="com.saas.qa.api.testcase.open.circle.StoreCircleSyncTest">
    <failure type="java.lang.AssertionError" message="结果不符合预期 expected [1] but found [open_store_001]">
        <![CDATA[java.lang.AssertionError: 结果不符合预期 expected [1] but found [open_store_001]
at com.saas.qa.api.testcase.open.circle.StoreCircleSyncTest.testCircleSync_MissingRequired(StoreCircleSyncTest.java:67)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at com.saas.qa.api.utils.TestReportGenerator.runTests(TestReportGenerator.java:73)
at com.saas.qa.api.utils.TestReportGenerator.generateAndOpenReport(TestReportGenerator.java:53)
at com.saas.qa.api.utils.TestReportGenerator.main(TestReportGenerator.java:154)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testCircleSync_MissingRequired -->
  <testcase name="testCircleSync_Success" time="5.147" classname="com.saas.qa.api.testcase.open.circle.StoreCircleSyncTest"/>
</testsuite> <!-- Store Circle Sync Tests -->
